# Generated by Django 5.2.7 on 2025-10-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_comment_options_remove_comment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Số lượt xem sản phẩm'),
        ),
    ]
