# Generated by Django 5.2.7 on 2025-10-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='đếm số lần xem sản phẩm'),
        ),
    ]
